version: '2'
services:
  erp:
    build: .
    ports:
      - "8080:80"
    volumes:
      - "..:/var/www/erp"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:latest
    restart: always
    volumes:
      - "./.db:/var/lib/mysql"
    ports:
      - "3316:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
      MYSQL_USER: erp
      MYSQL_PASSWORD: erp
