version: '3.4'
services:
  web:
    build: php-apache
    ports:
      - "3000:80"
    volumes:
      - "..:/var/www/html"
    depends_on:
      - mariadb
    links:
      - mariadb
  mariadb:
    build: mariadb
    volumes:
      - "./mariadb/.mysql:/var/lib/mysql"
  adminer:
    image: adminer
    ports:
      - "3300:8080"
    depends_on:
      - mariadb
    links:
      - mariadb
