version: '2'
services:
  web:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ".:/var/www/html"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:latest
    volumes:
      - ".db:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
