version: '2'
services:
  web:
    build: ./web
    hostname: 'drupal7.com'
    ports:
      - "8080:80"
    volumes:
      - "./web/drupal:/var/www/html"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql
    restart: always
    volumes:
      - "./.data/db:/var/lib/mysql"
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
